export const authNavigationUrls = {
  createNewPassword: () => '/auth/create-new-password',
  forgotPassword: () => '/auth/forgot-password',
  googleCallback: () => `/auth/callback/google`,
  home: () => '/',
  linkConfirmation: () => '/auth/registration-confirmation',
  linkExpired: (email?: string) => `/auth/link-expired?email=${email}`,
  logout: () => '/auth/logout',
  main: () => '/main',
  newPasswordConfirmation: () => '/auth/new-password-confirmation',
  passwordRecovery: () => '/auth/recovery',
  privacyPolicy: () => '/auth/privacy-policy',
  signIn: () => '/auth/sign-in',
  signUp: () => '/auth/sign-up',
  termsOfService: () => '/auth/terms-of-service',
}

export const old_authApiUrls = {
  baseUrl: () => 'https://api.freedomindz.site',
  createNewPassword: () => '/api/v1/auth/new-password',
  deleteAvatar: () => '/api/v1/avatar',
  getMe: () => '/api/v1/auth/me',
  getProfile: () => '/api/v1/profile',
  githubOAuthPage: () => '/api/auth/github',
  googleOAuthPage: () => '/api/auth/google',
  logout: () => '/api/v1/auth/logout',
  openGithubOAuth: () => '/api/auth/github',
  openGoogleOAuth: () => '/api/auth/google',
  passwordRecovery: () => '/api/v1/auth/recovery',
  refreshMe: () => '/api/v1/auth/refresh-token',
  registrationConfirmation: () => '/api/v1/auth/registration-confirmation',
  resendEmail: () => '/api/v1/auth/resend-code',
  signIn: () => '/api/v1/auth/login',
  signUp: () => '/api/v1/auth/registration',
  signWithGithub: () => '/api/auth/github/register',
  signWithGoogle: () => '/api/auth/google/register',
  updateProfile: () => '/api/v1/profile',
  uploadAvatar: () => '/api/v1/avatar/upload',
}

export const authApiUrls = {
  checkRecoveryCode: () => '/api/v1/auth/check-recovery-code' as const,
  createNewPassword: () => '/api/v1/auth/new-password' as const,
  deleteAvatar: () => '/api/v1/users/profile/avatar' as const,
  getMe: () => '/api/v1/auth/me' as const,
  getProfile: () => '/api/v1/users/profile' as const,
  loginGithubOAuth: () => '/api/v1/auth/github/login' as const,
  //----------------------------------------------
  loginGoogleOAuth: () => '/api/v1/auth/google/login' as const,
  passwordRecovery: () => '/api/v1/auth/recovery' as const,
  refreshMe: () => '/api/v1/auth/update-tokens' as const,
  registrationConfirmation: () => '/api/v1/auth/registration-confirmation' as const,
  resendEmail: () => '/api/v1/auth/registration-email-resending' as const,
  signIn: () => '/api/v1/auth/login' as const,
  signOut: () => '/api/v1/auth/logout' as const,
  signUp: () => '/api/v1/auth/registration' as const,
  updateProfile: () => '/api/v1/users/profile' as const,
  uploadAvatar: () => '/api/v1/users/profile/avatar' as const,
}
