import Image, { ImageProps } from 'next/image'

import { PostImageViewModel } from '@/app/services/autoGeneratedOpenApi/postsApi'

type GalleryItemProps = {
  src: PostImageViewModel
  alt?: string
} & ImageProps
export const GalleryItem = ({ src, alt, ...props }: GalleryItemProps) => {
  return <Image src={src} alt={alt} {...props} />
}
